name: Build
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.100-preview.8.20417.9"

      - name: Build
        run: |
          dotnet build src/90x/InitOnly/InitOnly.csproj
          dotnet build src/90x/NewExpression/NewExpression.csproj
          dotnet build src/90x/PatternMatching/PatternMatching.csproj
          dotnet build src/90x/Records/Records.csproj
          dotnet build src/90x/TopLevelStatements/TopLevelStatements.csproj
